{{- $apiVersion := "batch/v1beta1" }}
{{- if .Values.cronjob.apiVersion -}}
{{- $apiVersion = .Values.cronjob.apiVersion -}}
{{- else if .Capabilities.APIVersions.Has "batch/v1" -}}
{{- $apiVersion = "batch/v1" }}
{{- end }}
apiVersion: {{ $apiVersion }}
kind: CronJob
metadata:
  name: {{ include "gitea-backup.fullname" . }}
  labels:
    {{- include "gitea-backup.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "gitea-backup.selectorLabels" . | nindent 12 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "gitea-backup.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - "bin/bash"
              - "-c"
              - "gitea-backup"
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            volumeMounts:
              - name: config
                mountPath: /config/gitea-backup
              {{- if .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 14 }}
              {{- end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          volumes:
            - name: config
              configMap:
                name: {{ template "gitea-backup.fullname" . }}-config
                defaultMode: 420
            {{- if .Values.extraVolumes }}
            {{- toYaml .Values.extraVolumes | nindent 12 }}
            {{- end }}
