{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "gitea-backup.fullname" . }}-operator
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - "get"
    - "watch"
    - "list"
- apiGroups:
    - ""
  resources:
    - "pods/exec"
    - "pods/cp"
  verbs:
    - "create"
    - "update"
    - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "gitea-backup.fullname" . }}-operator-rolebinding
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "gitea-backup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ template "gitea-backup.fullname" . }}-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
