---
- name: Send ping to healthcheck URL
  uri:
    url: "{{ _backup.healthcheckUrl }}"
    force: yes
    timeout: "10"
    validate_certs: no
  when:
    - _backup.healthcheckUrl is defined
  ignore_errors: yes

