---
- hosts: backup
  roles:
    - ten7.flightdeck_base
  tasks:
    - name: Create a temp directory to store files needed by the run
      tempfile:
        state: directory
        prefix: "ansible-deploy-"
      register: _run_temp_dir
      notify:
        - clear caches
    - name: Install necessary software.
      community.general.apk:
        name: "{{ _packages | join(',') }}"
        state: present
        update_cache: yes
      notify:
        - clear apk cache
      vars:
        _packages:
          - "openssh-client"
          - "py3-boto3"
          - "py3-botocore"
          - "py3-chardet"
          - "py3-pip"
          - "py3-urllib3"
    - name: Install the additional packages from pip
      pip:
        name:
          - "kubernetes"
          - "s3cmd"
        extra_args: "--no-cache-dir"
    - name: Get the stable version of Kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
        dest: "{{ _run_temp_dir.path }}/stable.txt"
    - name: Download kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ lookup('file', _run_temp_dir.path + '/stable.txt' )}}/bin/linux/amd64/kubectl"
        dest: "/bin/kubectl"
        owner: "root"
        group: "backup"
        mode: "u=rwx,g=rx,o="
    - name: Deploy key scripts.
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "backup"
        group: "backup"
        mode: "u=rx,g=rx,o="
      loop:
        - src: "templates/gitea-backup.sh.j2"
          dest: "/usr/local/bin/gitea-backup"
    - name: Create the backup directory
      file:
        path: "/backups"
        state: directory
        owner: "backup"
        group: "backup"
        mode: "u=rwx,g=rwx,o="
    - name: Update permissions of key directories
      file:
         path: "{{ item }}"
         state: directory
         owner: "backup"
         group: "backup"
         mode: "u=rwx,g=rwx,o="
      loop:
        - "/ansible"
        - "/home/backup/.ssh"
  handlers:
    - name: clear caches
      shell: >
        rm -rf {{ item }}
      args:
        warn: no
      loop:
        - "/tmp/*"
        - "/var/cache/apk/*"
        - "/var/www/.composer/cache"
        - "/var/www/.npm/_cacache"
        - "/root/.ansible/tmp"
        - "/root/.cache"
