---
- name: Rotate files if a retainCount is set.
  shell: >
    s3cmd mv
    {% if _backup.endpoint is defined %}
    --host={{ _backup.endpoint }}
    --host-bucket={{ _backup.hostBucket }}
    {% endif %}
    --access_key={{ _access_key }}
    --secret_key={{ _secret_key }}
    --acl-private
    s3://{{ _src_path }} s3://{{ _dest_path }}
  loop: "{{ range((_backup.retainCount -2), -1, -1) }}"
  vars:
    _access_key: "\
      {% if _backup.accessKeyFile is defined %}\
      {{ lookup('file', _backup.accessKeyFile) }}\
      {% else %}\
      {{ _backup.accessKey | default(omit) }}\
      {% endif %}"
    _secret_key: "\
      {% if _backup.secretKeyFile is defined %}\
      {{ lookup('file', _backup.secretKeyFile) }}\
      {% else %}\
      {{ _backup.secretKey | default(omit) }}\
      {% endif %}"
    _src_path: "\
      {{ _backup.bucket }}/\
      {% if _backup.path is defined %}\
      {{ _backup.path }}/\
      {% endif %}\
      {{ _backup_file_prefix }}-{{ item }}.{{ _backup_file_suffix }}"
    _dest_path: "\
      {{ _backup.bucket }}/\
      {% if _backup.path is defined %}\
      {{ _backup.path }}/\
      {% endif %}\
      {{ _backup_file_prefix }}-{{ item + 1 }}.{{ _backup_file_suffix }}"
  when:
    - _backup.retainCount | default(1) > 1
  ignore_errors: true
  no_log: "{{ flightdeck_debug | default(false) | ternary(false, true) }}"

- name: Push backup to S3
  amazon.aws.aws_s3:
    bucket: "{{ _backup.bucket }}"
    object: "{{ _backup.path | default('') }}/{{ _backup_file_prefix }}-0.{{ _backup_file_suffix }}"
    src: "{{ _backup_file_path }}"
    mode: put
    s3_url: "{{ _backup.s3Url | default(omit) }}"
    region: "{{ _backup.region | default(omit) }}"
    encrypt: no
    permission: private
    aws_access_key: "\
      {% if _backup.accessKeyFile is defined %}\
      {{ lookup('file', _backup.accessKeyFile) }}\
      {% else %}\
      {{ _backup.accessKey | default(omit) }}\
      {% endif %}"
    aws_secret_key: "\
      {% if _backup.secretKeyFile is defined %}\
      {{ lookup('file', _backup.secretKeyFile) }}\
      {% else %}\
      {{ _backup.secretKey | default(omit) }}\
      {% endif %}"
  no_log: "{{ flightdeck_debug | default(false) | ternary(false, true) }}"

- include_tasks: "httpPing.yml"
