---
- name: Copy identity files to our temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ _run_temp_dir.path }}/{{ item | basename }}"
    owner: "backup"
    group: "backup"
    mode: "u=rw,g=,o="
    force: yes
  loop:
    - "{{ _backup.keyFile }}"
    - "{{ _backup.pubKeyFile }}"

- name: Create the remote directory
  shell: >
    ssh
    -i {{ _run_temp_dir.path }}/{{ _backup.keyFile | basename }}
    -o "StrictHostKeyChecking=no"
    -o "UserKnownHostsFile=/dev/null"
    -o IdentitiesOnly=yes
    {{ _backup.user }}@{{ _backup.host }}
    mkdir -p {{ _backup.path }}
  when:
    - _backup.path is defined

- name: Rotate files if a retainCount is set.
  shell: >
    ssh
    -i {{ _run_temp_dir.path }}/{{ _backup.keyFile | basename }}
    -o "StrictHostKeyChecking=no"
    -o "UserKnownHostsFile=/dev/null"
    -o IdentitiesOnly=yes
    {{ _backup.user }}@{{ _backup.host }}
    mv -f
    {% if _backup.path is defined %}{{ _backup.path }}/{% endif %}{{ _backup_file_prefix }}-{{ item }}.{{ _backup_file_suffix }}
    {% if _backup.path is defined %}{{ _backup.path }}/{% endif %}{{ _backup_file_prefix }}-{{ item + 1 }}.{{ _backup_file_suffix }}
  loop: "{{ range((_backup.retainCount -2), -1, -1) }}"
  when:
    - _backup.retainCount | default(1) > 1
  ignore_errors: true

- name: Upload the backup.
  shell: >
    scp
    -o "StrictHostKeyChecking=no"
    -o "UserKnownHostsFile=/dev/null"
    -o IdentityFile={{ _run_temp_dir.path }}/{{ _backup.keyFile | basename }}
    -o IdentitiesOnly=yes
    -P {{ _backup.port | default('22') }}
    {{ _backup_file_path }}
    {{ _backup.user }}@{{ _backup.host }}:{% if _backup.path is defined %}{{ _backup.path }}/{% endif %}{{ _backup_file_prefix }}-0.{{ _backup_file_suffix }}

- include_tasks: "httpPing.yml"
